services:
  mongo-tasks:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongo_task_data:/data/db

  keycloak-db:
    image: postgres
    environment:
      POSTGRES_HOST_AUTH: trust
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: keycloak_db
    ports:
      - '5433:5432'

  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - "8085:8080"
    restart: unless-stopped
    volumes:
      - postgres_kc_data:/var/lib/postgresql/data
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=postgres
      - DB_ADDR=keycloak-db
      - DB_DATABASE=keycloak_db
      - DB_SCHEMA=admin
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_PORT=5433
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENTSECRET}
      - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENTID}
    depends_on:
      - keycloak-db

    command: "start-dev"

  mysql-mail:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - mysql_mail_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  mysql-team:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - mysql_team_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: abc123

  email-service:
    depends_on:
      - mysql-mail
    image: venlomj/email-service
    ports:
      - "8082:8082"
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-mail
      MYSQL_DB_PORT: 3306

  team-service:
    depends_on:
      - mysql-team
      - email-service
      - task-service
    image: venlomj/task-team-service
    ports:
      - "8081:8081"
    environment:
      MAIL_SERVICE_BASEURL: email-service:8082
      TASK_SERVICE_BASEURL: task-service:8080
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: abc123
      MYSQL_DB_HOST: mysql-team
      MYSQL_DB_PORT: 3306

  task-service:
    depends_on:
      - mongo-tasks
      - email-service
    image: venlomj/task-service
    ports:
      - "8080:8080"
    environment:
      MONGODB_PORT: 27017
      MONGODB_HOST: mongo-tasks

  api-gateway:
    depends_on:
      - team-service
      - task-service
    image: venlomj/api-gateway
    ports:
      - "8083:8083"
    links:
      - team-service
      - task-service
    restart: on-failure
    environment:
      USER_SERVICE_BASEURL: team-service:8081
      TASK_SERVICE_BASEURL: task-service:8080

volumes:
  mongo_task_data:
  mysql_team_data:
  mysql_mail_data:
  postgres_kc_data:
