server:
  port: 8083

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    reactor.netty: INFO
    org.springframework.security: TRACE

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENTID}
            client-secret: ${GOOGLE_CLIENTSECRET}
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com
          jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true

  cloud:
    gateway:
      routes:
        - id: add-task
          uri: ${TASK_SERVICE_BASEURL:http://localhost:8080}
          predicates:
            - Path=/api/tasks/add
            - Method=POST
          filters:
            - SetPath=/api/tasks/add

        - id: update-task
          uri: ${TASK_SERVICE_BASEURL:http://localhost:8080}
          predicates:
            - Path=/api/tasks/update/**
            - Method=PUT
          filters:
            - SetPath=/api/tasks/update/{taskCode}

        - id: delete-task
          uri: ${TASK_SERVICE_BASEURL:http://localhost:8080}
          predicates:
            - Path=/api/tasks/delete/**
            - Method=DELETE
          filters:
            - SetPath=/api/tasks/delete/{taskCode}

        - id: get-all-tasks
          uri: ${TASK_SERVICE_BASEURL:http://localhost:8080}
          predicates:
            - Path=/api/tasks/get/all
            - Method=GET
          filters:
            - SetPath=/api/tasks/get/all

        - id: get-tasks-by-rNumber
          uri: ${TASK_SERVICE_BASEURL:http://localhost:8080}
          predicates:
            - Path=/api/tasks/get-by-rNumber/**
            - Method=GET
          filters:
            - SetPath=/api/tasks/get-by-rNumber/{rNumber}

        - id: add-task-for-member
          uri: ${TEAM_SERVICE_BASEURL:http://localhost:8081}
          predicates:
            - Path=/api/member-task/add-for-member/**
            - Method=POST
          filters:
            - SetPath=/api/member-task/add-for-member/{rNumber}

        - id: update-member
          uri: ${TEAM_SERVICE_BASEURL:http://localhost:8081}
          predicates:
            - Path=/api/member/update/**
            - Method=PUT
          filters:
            - SetPath=/api/member/update/{rNumber}

        - id: delete-member
          uri: ${TEAM_SERVICE_BASEURL:http://localhost:8081}
          predicates:
            - Path=/api/member/delete/**
            - Method=DELETE
          filters:
            - SetPath=/api/member/delete/{rNumber}

        - id: get-all-members
          uri: ${TEAM_SERVICE_BASEURL:http://localhost:8081}
          predicates:
            - Path=/api/member/get/all
            - Method=GET
          filters:
            - SetPath=/api/member/get/all

        - id: get-member-by-rNumber
          uri: ${TEAM_SERVICE_BASEURL:http://localhost:8081}
          predicates:
            - Path=/api/member/get/**
            - Method=GET
          filters:
            - SetPath=/api/member/get/{rNumber}

        - id: remove-member-from-team
          uri: ${TEAM_SERVICE_BASEURL:http://localhost:8081}
          predicates:
            - Path=/api/member/remove-from-team
            - Method=DELETE
          filters:
            - SetPath=/api/member/remove-from-team/

        - id: add-department
          uri: ${TEAM_SERVICE_BASEURL:http://localhost:8081}
          predicates:
            - Path=/api/dep/add
            - Method=POST
          filters:
            - SetPath=/api/dep/add

        - id: get-all-departments
          uri: ${TEAM_SERVICE_BASEURL:http://localhost:8081}
          predicates:
            - Path=/api/dep/get/all
            - Method=GET
          filters:
            - SetPath=/api/dep/get/all

        - id: get-department-by-code
          uri: ${TEAM_SERVICE_BASEURL:http://localhost:8081}
          predicates:
            - Path=/api/dep/get/**
            - Method=GET
          filters:
            - SetPath=/api/dep/get/{depCode}

        - id: add-team
          uri: ${TEAM_SERVICE_BASEURL:http://localhost:8081}
          predicates:
            - Path=/api/team/add
            - Method=POST
          filters:
            - SetPath=/api/team/add

        - id: assign-members-to-team
          uri: ${TEAM_SERVICE_BASEURL:http://localhost:8081}
          predicates:
            - Path=/api/team/assign-members/**
            - Method=POST
          filters:
            - SetPath=/api/team/assign-members

        - id: update-team
          uri: ${TEAM_SERVICE_BASEURL:http://localhost:8081}
          predicates:
            - Path=/api/team/update/**
            - Method=PUT
          filters:
            - SetPath=/api/team/update/{teamNumber}

        - id: get-all-teams
          uri: ${TEAM_SERVICE_BASEURL:http://localhost:8081}
          predicates:
            - Path=/api/team/get/all
            - Method=GET
          filters:
            - SetPath=/api/team/get/all

        - id: get-team-by-teamNumber
          uri: ${TEAM_SERVICE_BASEURL:http://localhost:8081}
          predicates:
            - Path=/api/team/get/**
            - Method=GET
          filters:
            - SetPath=/api/team/get/{teamNumber}

        - id: delete-team
          uri: ${TEAM_SERVICE_BASEURL:http://localhost:8081}
          predicates:
            - Path=/api/team/delete/**
            - Method=DELETE
          filters:
            - SetPath=/api/team/delete/{teamNumber}
